### ISSUE TITLE
🐞 [23.mm.dd] 누구있슈 #8282

### ISSUE THREAD

**Issue by Stilllee** [phoenix-kurly/phoenix-kurly#2]
> ✅ 원하는 기능이 구현되지 않는 경우, 어떤 기능을 구현하고자 했는지, 기능을 구현하기 위해 코드를 어떻게 작성했는지, 어떻게 구현됐는지 등 상황을 파악할 수 있게 코드와 함께 상세하게 작성해주세요.
✅ 에러 메시지가 발생한 경우, 함께 첨부해주세요.
✅ 필요한 경우, 이미지와 동영상을 첨부해주세요.

> ✅ 문제 상황을 해결한 경우, 제목에 이슈 번호를 함께 작성해주세요.
✅ 어떻게 해결했는지 코드와 함께 상세하게 설명해주세요. (어느 부분이 문제였는지, 어떻게 해결했는지 등. 참고 링크가 있는 경우 함께 작성) 

> - 필수 내용: 문제 상황, 코드, 에러 메시지, 이슈 번호(해결한 경우)
> - 선택 사항: 이미지, 동영상, 참고 링크

## 문제 상황

여기에 문제 상황을 상세하게 작성해주세요.

## 코드
코드를 올릴 때, VS Code 캡쳐본과 함께 해당 코드를 복사해서 올려주세요. 
에러메시지가 있는 경우, 에러메시지 캡쳐본과 함께 에러메시지를 복사해서 올려주세요.

## 기타
이미지, 동영상, 참고 링크

**Comment by Sunny-SunHeeJung** [comment]
테스트 완료
