### ISSUE TITLE
🗓️ [오프] 0204 phoenix 주말 작업

### ISSUE THREAD

**Issue by Sunny-SunHeeJung** [phoenix-kurly/phoenix-kurly#24]
## 날짜
2023.02.04 12시

## 장소 
영등포 정선희님 집

## 주제
html,css 공통작업 충돌 방지

## 참가자
강보경 박일범 배성재 정선희

## 공통작업
깃 관리
## 목적
오프라인을 통해 프로젝트 진행

**Comment by baeseongjae** [comment]
탱탱한 쪼르면이 기대뎁니더ㅎㅎ

**Comment by codewarf** [comment]
탱탱한 면발 기대합니다 ㅎㅎ
