### ISSUE TITLE
🐞 [23.02.04] git push reject 문제 해결 #34

### ISSUE THREAD

**Issue by hungerbk** [phoenix-kurly/phoenix-kurly#37]
## 문제 상황

메인 브랜치에서 풀을 한 뒤, 그 내용을 취소하고 다시 작업을 하려는 상황에 원격 저장소의 커밋 시점과 로컬 저장소의 커밋 시점이 맞지 않아 푸시가 되지 않는 문제 발생 (기억이 나지 않았지만.. 중간에 원격 저장소에 푸시를 했던 것 같다.)

## 코드
``git reset --hard 커밋 아이디``
원하는 시점으로 HEAD를 이동하는 명령어 (돌아가는 커밋 시점 이후의 커밋 내용은 삭제한다)
(e.g. ``git reset --hard e6f1edcf``)

``git push remote이름 브랜치이름 -f``
원격 저장소에 로컬 저장소의 내용을 강제로 푸시 (개인 저장소라 사용했지만, 공용 저장소에서는 주의해서 사용해야 한다....)
(e.g. ``git push origin register -f``)

이 이후에 메인 브랜치에서 풀 하지 않고, ``npx degit phoenix-kurly/phoenix-kurly/client/assets#main client/assets`` 를 이용해서 파일을 추가한 뒤 필요한 작업을 진행함

## 기타
<img width="455" alt="스크린샷 2023-02-04 오전 12 32 51" src="https://user-images.githubusercontent.com/43366461/216643014-2b72836f-0db4-422b-99e9-2295aff2733d.png">

메인브랜치의 커밋 이력이 남아있지 않음!

**Comment by codewarf** [comment]
훌륭합니다~
