### ISSUE TITLE
🗓️ [온라인] 0207 phoenix 평일작업

### ISSUE THREAD

**Issue by Sunny-SunHeeJung** [phoenix-kurly/phoenix-kurly#59]
## 날짜
2023.02.07

## 장소 
디스코드 랩 13조

## 주제
정각마다 현재 진행상황 공유
js에 집중

## 참가자
강보경 박유림 박일범 배성재 이에스더 정선희

## 공통작업

- js 들어가기

-  충돌 나거나 그러면 그것을 해결하는과정 가능하다면 스크린샷으로 남기기
- #29 통해 버그 해결 close issue 

모듈수정
```
:root {
  /* color */
  --purple: #5f0080;
  --white: #fff;
  --black: #333;
  --dark-grey: #898989;
  --grey: #999;
  --orange: #fa622f;
  --light-gray: #e1e1e1;

  --primary-color: var(--purple);
  --accent-color: var(--orange);

  /* space  */
  --spacing-sxxs: 2px;
  --spacing--xxs: 4px;
  --spacing-xs: 8px;
  --spacing-sm: 12px;
  --spacing-base: 16px;
  --spacing-md: 20px;
  --spacing-lg: 24px;
  --spacing-xl: 32px;

  --minus-spacing-sxxs: -2px;
  --minus-spacing--xxs: -4px;
  --minus-spacing-xs: -8px;
  --minus-spacing-sm: -12px;
  --minus-spacing-base: -16px;
  --minus-spacing-md: -20px;
  --minus-spacing-lg: -24px;
  --minus-spacing-xl: -32px;

  /* font-size */
  --text-xxs: 10px;
  --text-xs: 12px;
  --text-sm: 14px;
  --text-base: 16px;
  --text-md: 18px;
  --text-lg: 21.33px;
  --text-xl: 37.9px;

  /* font-weight */
  --text-400: 400;
  --text-600: 600;
  --text-700: 700;
}

.gradient-effect {
  background: #ccc linear-gradient(to bottom, #ccc, #eee);
  border: 1px solid #aaa;
  border-radius: 5px;
  padding: 10px;
}

.accent-color {
  color: #e85e2c;
}

.text-xl {
  font-size: 1.5rem;
  font-weight: 700;
}

.margin-top-default {
  margin-top: 20px;
}
.margin-top-thin {
  margin-top: 5px;
}
.margin-top-normal {
  margin-top: 10px;
}
.margin-top-large {
  margin-top: 15px;
}

.margin-top-10 {
  margin-top: 10px;
}
.margin-top-15 {
  margin-top: 15px;
}
```

**Comment by hungerbk** [comment]
자바스크립트 구현
- [x] 비밀번호 글자수 확인
- [x] 핸드폰, 생년월일에 숫자만 입력가능하게 하기
-> 이런 validation을 어떻게 보여줄지는 좀더 고민해야 할 듯
- [ ] 회원가입 시 unique id 생성
- [ ] 입력한 값을 data.json, local storage에 저장
- [x] 핸드폰 인증번호 보내기 누르면 팝업으로 띄워주기
- [x] 약관 전체선택, 해제, 일부선택 시 전체선택 변화 주는 함수 구현

**Comment by Sunny-SunHeeJung** [comment]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/83347465/217121467-8c9b72aa-625c-473e-8e2c-cc00f7c2d4db.png">

-  버튼 클릭시 글씨 색  색 변경 구현하기

-  자바스크립트 구현

**Comment by codewarf** [comment]
- > 상세페이지 css 아코디언버튼 구현 마무리 및 js 모달창 구현 작업
장바구니페이지 css 아코디언버튼구현 작업

**Comment by yurimpark** [comment]
- 상세페이지 버튼들 js 구현 작업
- [x] 찜
- [ ] 장바구니
- [ ] nav

**Comment by Stilllee** [comment]
- pr 충돌해결
- header 상단메뉴(네비) 변경되는 스타일 작업
- 카테고리 이미지 삽입 및 스타일 조정
- page switch(마켓칼리, 뷰티칼리) js
- 특정 아이콘 링크연결 구상
- top-banner 닫기동작 구현

**Comment by baeseongjae** [comment]
- 상품리스트 슬라이드 기능 구현(swiper)
- 최근 본 상품 기능 구현(localstorage 활용)
- 장바구니 모달창 , 메인 모달 js 구현
