### ISSUE TITLE
🗓️ [온라인] 0208 phoenix 평일작업

### ISSUE THREAD

**Issue by Sunny-SunHeeJung** [phoenix-kurly/phoenix-kurly#84]
## 날짜
2023.02.08

## 장소 
디스코드

## 주제
2월 8일 할 일

## 참가자
강보경 박유림 박일범 배성재 이에스더 정선희

## 공통작업
발표 전날
## 목적
다들 끝까지 최선을 다헤서 화이팅 하기

**Comment by hungerbk** [comment]
- [ ] 회원가입 기능 구현
- [ ] 로그인 기능 구현

**Comment by Sunny-SunHeeJung** [comment]
상품리스트 css+js 버튼 / 리드미/ 위키

**Comment by yurimpark** [comment]
- [x] navbar sticky 안먹힘 해결하기
- [x] 장바구니 넣기 버튼 누르면 버블 4초 띄우기
- [x] 제품 수량 버튼 작동
- [x] 이미지 연결 안된거 고치기
- [x] 상세페이지 일범님 작업한거 합치기
- [x] 후기작성 버튼 누르면 후기쓰기 창 띄우기
- [x] 문의하기 창 후기작성 창 재활용해서 만들기
- [x] 문의하기 버튼 누르면 문의 창 띄우기

**Comment by Sunny-SunHeeJung** [comment]
병합중 css 해결하기
